"""add columnt to quote table

Revision ID: 949c07c74aed
Revises: 0b938d0885b7
Create Date: 2025-04-09 01:52:24.882934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '949c07c74aed'
down_revision: Union[str, None] = '0b938d0885b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mobile_bar_requests', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mobile_bar_requests', 'created_at')
    # ### end Alembic commands ###
